name: Update Screenshots

on: [push, workflow_dispatch]

jobs:
  update-screenshots:
    permissions:
      contents: write
    uses: OMICRONEnergyOSS/oscd-gh-workflows/.github/workflows/update-screenshots.yml@main
